### ISSUE TITLE
Wrap in node module

### ISSUE THREAD

**Issue by tmcw** [tmcw/big-printer#3]

**Comment by bcomnes** [comment]
Help wanted?  Interested in landing this on npm?

**Comment by tmcw** [comment]
Definitely! There might be some tricks worth stealing in [screenshot-stream](https://github.com/kevva/screenshot-stream)

**Comment by bcomnes** [comment]
ooh nice, good find.

**Comment by tmcw** [comment]
Done https://github.com/tmcw/big-printer#installation

**Comment by bcomnes** [comment]
Awesome!  Sorry, I was never able to finish my attempt.
